FROM node:15-alpine as build-stage

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY ./ ./

RUN npm build



FROM nginx:stable-alpine

COPY --from=build-stage /usr/src/app/build /usr/share/nginx/html

COPY /nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

